version: '3.9'

volumes:
  pg_data:
  redis_data:
  backend:

services:
  postgres:
    image: postgres:13.3
    container_name: ${DB_HOST}
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    env_file: .env
    container_name: ${REDIS_HOST}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/orders
    build:
      context: .
    ports:
      - "8000:8000"
    command: 
      - sh
      - -c
      - |
        python manage.py makemigrations backend --noinput
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
      
  worker:
    build:
      context: .
    volumes:
      - .:/orders
    command: celery -A orders worker --loglevel=INFO
    # command: python -m celery -A orders.celery_app worker --loglevel=INFO
    depends_on:
      - postgres 
      - redis
  
